<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>网页正文提取</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{{url_for('static', filename='pure-min.css')}}">
</head>
<body>
    {% block body %}
    {% endblock %} 
<div class="pure-g">
    <div class="pure-u-1 footer text-center">
        <p>Copyright 2016 tomwei7.com</p>
    </div>
</div>
</body>
</html>
