<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <title>正文提取</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{{url_for('static', filename='index.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='pure-min.css')}}">
</head>
<body>
    <div class="container">
        <div class="header">
        </div>
        <div class="form-cent pure-form">
            <form action="/extract">
                <div class="row">
                    <input class="url-ipt" type="text" name="url" id="url" placeholder="需要提取的网页地址">
                    <button class="url-btn pure-button-primary pure-button" type="submit">提取</button>
                </div>
                <div class="row text-center url-option">
                    <input type="radio" name="show_type" value="text" checked>  纯文本
                    <input type="radio" name="show_type" value="html">  富文本(测试功能)
                </div>
            </form>
        </div>
        <div class="footer">
        </div>
    </div>
</body>
</html>
